### ISSUE TITLE
(basic-types.md) 500에러 발생 시킴

### ISSUE THREAD

**Issue by kangsLee** [triplepy/kotlin-web-site#5]
@hyunji92 

python으로 정상 실행 되지 않음.

**Comment by kangsLee** [comment]
에러와는 무관하지만 
상단 메타태그는 title: "<이 부분>" 만 번역 해야함. 
layout 같은 경우는 템플릿과 매칭되어 자동 삽입 되는데 한 글자라도 달라진다면 정상적으로 불러오지 못함.

**Comment by hyunji92** [comment]
@kangsLee  python 파일을 따로 수정해서 커밋한거는 없는데 왜 실행되지 않는지 이유좀;;;;;;;ㅠㅠ
